### ISSUE TITLE
Doas support

### ISSUE THREAD

**Issue by abb128** [korcankaraokcu/PINCE#119] opened 2022-04-13 23:57 UTC
This is looking like an excellent tool so far, but unfortunately I wasn't able to use it as PINCE doesn't work at all when opendoas is being used instead of sudo. Maybe polkit or something could be supported to allow use when doas instead of sudo is installed?

**Comment by korcankaraokcu** [comment] 2022-04-25 16:49
Duplicate of https://github.com/korcankaraokcu/PINCE/issues/112

**Closed by korcankaraokcu** 2022-04-25 16:49 UTC
Labels: duplicate
