### ISSUE TITLE
PINCE unusable in Arch Linux

### ISSUE THREAD

**Issue by MuradTroll** [korcankaraokcu/PINCE#126] opened 2022-07-09 09:38 UTC
PINCE is unusable in Arch Linux. I am not sure where it fails, but I can't scan any values of the memory. Also after attaching, the process gets halted but PINCE is still showing that no process is attached. At this point (after attaching a process) I get errors in my terminal. Also the process selection window does not close itself after selecting a process, which is not intended I suppose.
I am starting pince through terminal without sudo. There are lots of errors, here are some snippets

> Last command: source gdb_python_scripts/GDBCommandExtensions.py
> &"Traceback (most recent call last):\n"
> &"  File \"gdb_python_scripts/GDBCommandExtensions.py\", line 27, in <module>\n"
> &"    from libpince import SysUtils, type_defs, common_regexes\n"
> &"  File \"/usr/share/PINCE/libpince/SysUtils.py\", line 32, in <module>\n"
> &"    from pygdbmi import gdbmiparser\n"
> &"ModuleNotFoundError: No module named 'pygdbmi'\n"
> ^done
> 0.09264874458312988
> Last command: pince-parse-and-eval
> &"/dev/shm/PINCE-connection/2974/gdb_command.txt:1: Error in sourced command file:\n"
> &"Undefined command: \"pince-parse-and-eval\".  Try \"help\".\n"
> ^error,msg="/dev/shm/PINCE-connection/2974/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-parse-and-eval\".  Try \"help\"."
> Traceback (most recent call last):
>   File "/usr/share/PINCE/PINCE.py", line 1452, in pushButton_Open_clicked
>     if self.parent().attach_to_pid(pid):
>   File "/usr/share/PINCE/PINCE.py", line 1117, in attach_to_pid
>     attach_result = GDB_Engine.attach(pid, gdb_path)
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 607, in attach
>     inferior_arch = get_inferior_arch()
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 1155, in get_inferior_arch
>     if parse_and_eval("$rax") == "void":
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 1024, in parse_and_eval
>     return send_command("pince-parse-and-eval", send_with_file=True, file_contents_send=(expression, cast),
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 238, in send_command
>     output = pickle.load(open(recv_file, "rb"))
> EOFError: Ran out of input
> 

also

> Last command: pince-examine-expressions
> &"/dev/shm/PINCE-connection/2974/gdb_command.txt:1: Error in sourced command file:\n"
> &"Undefined command: \"pince-examine-expressions\".  Try \"help\".\n"
> ^error,msg="/dev/shm/PINCE-connection/2974/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-examine-expressions\".  Try \"help\"."
> Traceback (most recent call last):
>   File "/usr/share/PINCE/PINCE.py", line 2844, in on_process_stop
>     self.disassemble_expression("$pc")
>   File "/usr/share/PINCE/PINCE.py", line 2679, in disassemble_expression
>     program_counter = GDB_Engine.examine_expression("$pc").address
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 989, in examine_expression
>     return send_command("pince-examine-expressions", send_with_file=True, file_contents_send=[expression],
>   File "/usr/share/PINCE/libpince/GDB_Engine.py", line 238, in send_command
>     output = pickle.load(open(recv_file, "rb"))
> EOFError: Ran out of input
> 

When I try starting Pince through terminal with sudo, it doesn't even start, I get the error 

> Traceback (most recent call last):
>   File "/usr/share/PINCE/PINCE.py", line 31, in <module>
>     from libpince import GuiUtils, SysUtils, GDB_Engine, type_defs
>   File "/usr/share/PINCE/libpince/GuiUtils.py", line 24, in <module>
>     from . import SysUtils, type_defs, common_regexes
>   File "/usr/share/PINCE/libpince/SysUtils.py", line 32, in <module>
>     from pygdbmi import gdbmiparser
> ModuleNotFoundError: No module named 'pygdbmi'

note that pygdbmi is installed on my system.

**Comment by alimkoca** [comment] 2022-07-09 09:40
It was works on my system when I tried, interesting...

**Comment by MuradTroll** [comment] 2022-07-09 09:47
Clean install straight from github seems to solve it, I guess the AUR version is broken/too old

**Comment by MuradTroll** [comment] 2022-07-09 10:16
Although scanning works, the whole experience is still rather unstable, nearly every action results in error messages when the process is not halted (I don't know if that is intended, in CE you don't have to halt the process). Namely: 

- trying to change settings (like enabling GDB logging) does not seem to work, you have to restart PINCE to see effect

```
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 1913, in accept
    self.settings.setValue("Debug/ignored_signals", ",".join(self.handle_signals_data))
TypeError: can only join an iterable
```

- trying "find out what writes to this address" and double clicking a result does nothing:

```
Traceback (most recent call last):
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 3878, in tableWidget_Opcodes_item_double_clicked
    self.parent().memory_view_window.disassemble_expression(
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 2675, in disassemble_expression
    disas_data = GDB_Engine.disassemble(expression, offset)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 974, in disassemble
    output = send_command("disas /r " + expression + "," + offset_or_address)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 204, in send_command
    raise type_defs.InferiorRunningException
libpince.type_defs.InferiorRunningException: Inferior is running

```

- memory view seems to be botched, can't scroll, can't double click anything (unless process is halted)

```
Traceback (most recent call last):
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 3089, in widget_Disassemble_wheel_event
    self.tableWidget_Disassemble_scroll("next", instructions_per_scroll)
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 3113, in tableWidget_Disassemble_scroll
    new_address = GDB_Engine.find_address_of_closest_instruction(current_address, where, instruction_count)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 1063, in find_address_of_closest_instruction
    disas_data = disassemble(address, address + offset)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 974, in disassemble
    output = send_command("disas /r " + expression + "," + offset_or_address)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 204, in send_command
    raise type_defs.InferiorRunningException
libpince.type_defs.InferiorRunningException: Inferior is running
Traceback (most recent call last):
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 3089, in widget_Disassemble_wheel_event
    self.tableWidget_Disassemble_scroll("next", instructions_per_scroll)
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 3113, in tableWidget_Disassemble_scroll
    new_address = GDB_Engine.find_address_of_closest_instruction(current_address, where, instruction_count)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 1063, in find_address_of_closest_instruction
    disas_data = disassemble(address, address + offset)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 974, in disassemble
    output = send_command("disas /r " + expression + "," + offset_or_address)
  File "/home/murad/Downloads/pince/PINCE/libpince/GDB_Engine.py", line 204, in send_command
    raise type_defs.InferiorRunningException
libpince.type_defs.InferiorRunningException: Inferior is running
```

**Comment by korcankaraokcu** [comment] 2022-07-09 13:11
PINCE is warning you about the error both via GUI and console. `Inferior is running` means that you need to stop the inferior in order to use gdb related functionality. Read more in [here](https://github.com/korcankaraokcu/PINCE/wiki/Working-logic-of-PINCE)

**Comment by korcankaraokcu** [comment] 2022-07-09 13:31
```
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/murad/Downloads/pince/PINCE/PINCE.py", line 1913, in accept
    self.settings.setValue("Debug/ignored_signals", ",".join(self.handle_signals_data))
TypeError: can only join an iterable
```
I can reproduce this tho, going to fix it soon

**Comment by korcankaraokcu** [comment] 2022-07-09 13:52
> `TypeError: can only join an iterable`

This has been fixed, update PINCE with `git pull`

**Comment by alimkoca** [comment] 2022-07-09 13:53
> 

Perfect.

**Comment by TsarFox** [comment] 2022-07-09 16:01
Hello!

> note that pygdbmi is installed on my system.

I'll need a little more information to be able to help. How did you install it? Are you using an AUR helper?

The `PKGBUILD` for PINCE depends on `python-pygdbmi` in the AUR; if you installed it some other way, that may be causing the issue.

**Comment by zbirenbaum** [comment] 2022-10-29 07:23
I have this issue on arch running the git version. I even manually built all the deps...

**Comment by korcankaraokcu** [comment] 2022-10-30 00:35
I've installed it via installation script on a fresh system and cannot reproduce anything related to missing packages. Try using the installation script If you are having problems with AUR package

**Comment by zbirenbaum** [comment] 2022-10-30 19:16
> I've installed it via installation script on a fresh system and cannot reproduce anything related to missing packages. Try using the installation script If you are having problems with AUR package

That's what I did. Neither worked for me until I made modifications to some of the Python flies

**Comment by korcankaraokcu** [comment] 2022-10-30 22:48
Thanks for the info, I'll update this issue if I ever create virtual env within the installation

**Comment by korcankaraokcu** [comment] 2023-02-04 22:11
The installation script is updated and we've switched to pyqt6 now. Try doing a clean installation with the script and tell me if it works for you @zbirenbaum @MuradTroll

**Comment by korcankaraokcu** [comment] 2023-05-02 15:59
Installation script has been updated, try to reinstall from scratch. Do not use sudo while installing or launching the program, the scripts will handle it for you

**Comment by twosky2000** [comment] 2023-06-07 09:07
I had a little problem with the script: there was no apt refresh in the script, so there was a connection error on pyqt6
But updating apt before the script solved all.
Thank for your work!

**Comment by korcankaraokcu** [comment] 2023-06-07 11:29
Also, about this issue, @MuradTroll I've recently tested the script on a clean installation of archlinux, it seems to work without issues. I'll be closing this issue eventually if you don't reply

**Comment by ozgurozbek** [comment] 2023-08-12 01:40
It's been more than 2 months; the user has been inactive for over a year, fyi ^

**Comment by korcankaraokcu** [comment] 2023-09-24 21:46
It's working well in a clean setup, closing due to inactiveness

**Closed by korcankaraokcu** 2023-09-24 21:46 UTC
