### ISSUE TITLE
Disable most UI when no process is selected

### ISSUE THREAD

**Issue by MayeulC** [korcankaraokcu/PINCE#156] opened 2022-11-17 11:11 UTC
I killed PINCE after it crashed when I double-clicked a value in the result list (I'll try to reproduce).

I reopened it and forgot to select the process before scanning. The interface seemed to accept my inputs, but nothing was hapening, only some python tracebacks in the console.

I suggest disabling UI elements before the user selects a process to avoid that sort of oversight.

**Comment by korcankaraokcu** [comment] 2022-11-17 11:42
Yeah, it's a known issue. Most of the time it doesn't do anything other than giving errors in the console. When I've tried to close the process during a scan, scanmem complained about `/proc/$pid/mem` not existing and that's all, no crashes. How did you exactly crash it? I'd like to see the steps. Hard to say anything without being able to reproduce

**Comment by MayeulC** [comment] 2022-11-17 12:16
I since described the crash in #157 after reproducing. I just wrote that to give a bit more context: even if I know I have to open a process first, it's easy to forget that step.

**Comment by korcankaraokcu** [comment] 2022-11-17 13:12
I still cannot seem to reproduce. Can you write the steps one by one to clear confusion? Also, can you confirm that this issue does exist for other processes other than GNU Octave?

**Comment by korcankaraokcu** [comment] 2022-11-18 12:49
The issue for GNU Octave is continuing from #157, this issue will remain as an enhancement for UI

**Comment by neoh4x0r** [comment] 2022-11-25 20:34
@korcankaraokcu I think this feature/enchantment will also be addressed/resolved by the draft PR (N00byKing#1)

The solution was to add a check to most methods and do nothing if the GDB_Engine's PID was -1.

```
if GDB_Engine.currentpid == -1:
    return
````

**Comment by MayeulC** [comment] 2022-11-28 10:22
@neoh4x0r Indeed, this should resolve part of the issue if I get this correctly, but give no UI hint, as far as I know?

I'd approach this by writing a custom signal `isDebuggerConnected(bool)`, and connect that with the `setEnabled(bool)` slot `QWidget` elements have.

**Comment by korcankaraokcu** [comment] 2023-01-10 17:32
Mentioned PR has been merged and fixed this issue as well. But you are right about having an indicator, I'll create a new issue to continue from since the main concern of this issue has been satisfied. Continuing from #161

**Closed by korcankaraokcu** 2023-01-10 17:32 UTC
Labels: enhancement
