### ISSUE TITLE
GDB error

### ISSUE THREAD

**Issue by whitequill** [korcankaraokcu/PINCE#100] opened 2021-07-10 16:11 UTC
when I run `./PINCE.sh` I get the following meesage dialog:
> Unable to initalize GDB
> You might need to reinstall GDB or use the system GDB
> To change the current GDB path, check Settings->Debug

upon opening settings and clicking the folder to change the path the program crashes with the following error:

> (process:372193): Gtk-CRITICAL **: 12:01:09.775:  gtk_file_chooser_set_preview_widget: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed
error: 
Killed by signal 11.

Everything seemed to build without a hitch other then a lot of warnings.
[pince_err.txt](https://github.com/korcankaraokcu/PINCE/files/6795579/pince_err.txt)

I do not know if these have anything to do with the GTK file chooser failing.

**Comment by korcankaraokcu** [comment] 2021-07-11 10:21
I also couldn't make anything out of the error log, looks normal. What's your dist? That GTK error is something I've never faced before

**Comment by whitequill** [comment] 2021-07-14 09:32
Fedora 34

**Comment by korcankaraokcu** [comment] 2021-07-14 14:10
Fedora isn't supported right now. All of the scripts were written supported systems in mind. I'll reinstall a Fedora VM soon to see what we can do.

The error you are facing at the first second of the video indicates that PINCE failed to compile gdb. Try to change the gdb path manually by modifying the `PINCE.conf` in `~/.config/PINCE/`

About the GTK error: Actually, PINCE uses PyQT, not GTK, you shouldn't even be getting that error, it's very strange.

**Comment by korcankaraokcu** [comment] 2022-07-17 16:50
Linking this to #122

**Comment by korcankaraokcu** [comment] 2022-08-28 13:50
Fedora is now within the supported systems. Cannot reproduce this issue in a fresh install, closing the issue

**Closed by korcankaraokcu** 2022-08-28 13:50 UTC
