### ISSUE TITLE
Game freezes when attach (no signal)

### ISSUE THREAD

**Issue by thirder37** [korcankaraokcu/PINCE#242] opened 2024-02-19 14:08 UTC
I'm trying to attach to "The Finals" game, but the game freezes. There are no messages in the console about receiving a signal, and in the GUI there is no text STOPPED next to the process name. The F3 key doesn't help either.
I'm running on Ubuntu

**Comment by korcankaraokcu** [comment] 2024-02-19 14:29
That's interesting, I can think of a few scenarios:
- Are there any exceptions thrown into the console? Maybe PINCE is encountering an error and can't recover properly
- Does the game run with proton/wine? We've got a related issue #238
- A little less likely but maybe GDB is producing an unexpected output, can you enable GDB logging via settings and post the GDB log? It can be accessed in Memory Viewer->View->GDB Log File

**Comment by thirder37** [comment] 2024-02-19 14:41
1,3) There seem to be no errors, I am attaching a link to the logs, please look at https://pastes.dev/ZUiegCBkUd
2) The game is launched via steam using Proton Experemental

**Comment by korcankaraokcu** [comment] 2024-02-19 17:30
> The game is launched via steam using Proton Experemental

Yep, that's the problem. GDB has issues with proton/wine games and that reflects on PINCE too. I'll be closing this as a duplicate of #238 

PINCE works better with native targets, you can use scanmem for searching memory as an alternative

**Comment by korcankaraokcu** [comment] 2024-02-19 17:31
Duplicate of #238, closing

**Closed by korcankaraokcu** 2024-02-19 17:31 UTC
Labels: duplicate

**Comment by thirder37** [comment] 2024-02-19 17:35
when I use scanmem after scanning the game closes because it detects the scan

**Comment by korcankaraokcu** [comment] 2024-02-19 17:39
yeah because scanmem uses ptrace by default, you have to disable the ptrace option of it. You could also use [our scanmem fork](https://github.com/brkzlr/libscanmem-PINCE/tree/321fa6b18246ebcb2ac19c997a4e85ce7e54b82b). Ptrace is disabled by default in our fork

**Comment by korcankaraokcu** [comment] 2024-02-19 17:46
Yeah because scanmem uses ptrace by default, you have to disable the ptrace option of it. Also, I've noticed that the game you're working on is a multiplayer game. The game will obviously try to deploy protection measures. Unfortunately, this is only as far as I can go with helping. You'll have to figure out the rest by yourself for legal reasons
