### ISSUE TITLE
GNU Octave: Double-clicking a result in the match list freezes PINCE's UI

### ISSUE THREAD

**Issue by MayeulC** [korcankaraokcu/PINCE#157] opened 2022-11-17 11:18 UTC
Opening a GNU Octave process and double-clicking any matches in the match list freezes the UI

![image](https://user-images.githubusercontent.com/3952726/202431646-d7c4ab04-49f1-4638-bf2a-b3e452bf56db.png)

It generates the following console output before stopping to respond to user input and resize events:

```
Last command: Ctrl+c
5.435943603515625e-05
```

Arch Linux, PINCE installed from AUR, sway/wayland.

**Comment by MayeulC** [comment] 2022-11-17 12:37
Indeed, it seems specific to GNU Octave. Double-clicking also inputs a line break in Octave's console.

Quitting Octave unfreezes PINCE, and an error message is displayed: "GDB isn't initialized yet"

I have a lot of other GUI improvement suggestions to make, should I open tickets? The GUI is not responsive during scanning, and a scan can't be cancelled, for instance. I'd also like to have process start time displayed in the "open process" window (creation time of the corresponding `/proc/` entry. I can contribute some of the changes myself (the timeline would be ~months though), as I am familiar with PyQt and lower-level stuff as well.

**Comment by korcankaraokcu** [comment] 2022-11-17 13:10
> Quitting Octave unfreezes PINCE, and an error message is displayed: "GDB isn't initialized yet"

You can ignore that error, it's produced by a race condition that happens time to time

As for suggestions and improvements, go ahead. You can take your time as I also take long breaks from pince to focus on things going on within my life. I eventually come back to pince to fix bugs and accept PRs every now and then

**Comment by MayeulC** [comment] 2022-11-17 14:00
> I still cannot seem to reproduce. Can you write the steps one by one to clear confusion? Also, can you confirm that this issue does exist for other processes other than GNU Octave?

Answering here, let's not mix everything.

Running this on Arch, Octave installed from the depots.
PINCE is installed from the AUR, launched by `cd /usr/share/PINCE; pince`.

1. Open Octave in a terminal by typing "octave"
2. Attach to the `octave-gui` process
3. Launch a scan for "Unknown value" of whatever type, just to display something in the match view
4. Double click any entry in the match view

I should note that selecting an entry and clicking on the "down" arrow to add it to the list works, and it can be modified by double-clicking. Only the match list exhibits the issue.

**Comment by korcankaraokcu** [comment] 2022-11-17 19:19
I can confirm that this is reproducible, thanks for providing the steps

The culprit here is gdb, the usual way to break the process is to send `Ctrl+C` to gdb. But in this case, the input is captured by octave instead of gdb. Whenever you try to break with gdb you'll see octave omitting a new line instead and gdb being unresponsive

**Comment by korcankaraokcu** [comment] 2022-11-18 21:49
Sending `SIGINT` with `kill` command to gdb results in the same behavior. However, sending `STOP` to the octave not only stops the octave process but also triggers gdb to catch the signal. At first glance it seems to work but it produces two unwanted outcomes:

Firstly, terminal pushes octave to background as a stopped process and bash takes over
Secondly, it takes multiple `continue` commands to get back into running state instead of only one

I'll try to find something that works without any side effects

As for parsing text, unfortunately this is how gdb is being programmed for the past few decades. Pince uses `gdb-mi`, which provides a more structured interface to communicate with gdb. Graphical interfaces such as pince usually use that to communicate

**Comment by korcankaraokcu** [comment] 2022-11-24 06:22
gdb-mi specific functions such as `-exec-interrupt` doesn't work as well

**Comment by MayeulC** [comment] 2022-11-28 10:08
I've been wondering if you couldn't use GDB's native python scripting interface to control the debugging:

https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html#Python

That is, injecting a script in GDB that performs IPC with PINCE.

Since you [can extend](https://sourceware.org/gdb/current/onlinedocs/gdb/Breakpoints-In-Python.html#Breakpoints-In-Python) `gdb.Breakpoint`  and implement `Breakpoint.stop`, which gdb seems to use for checking whether your breakpoint stops the program, I think you could implement some IPC with PINCE in python inside that method (or as a separate thread, if it can run simultaneously), and reliably control GDB from there.

Have you toyed around with GDB's Python scripting interface? I am not sure what capabilities it provides, but interacting with a `gdb` object seems less prone to breakage than communicating with stdin/out and signals?

I may look more into it myself if I have some more spare time on the horizon.

Reading more into it though, I am not sure GDB supports stopping the inferior at will, only on breakpoints, or upon receiving signals/issuing system calls; so I am not sure how to handle that one.

**Comment by korcankaraokcu** [comment] 2022-12-04 18:58
> Have you toyed around with GDB's Python scripting interface?

Pince already makes use of it, [see here](https://github.com/korcankaraokcu/PINCE/tree/master/libpince/gdb_python_scripts)

The issue is mainly about not being able to give any commands other than signals while the process is running. So, using python would have no effect

> I think it might be worth it to ask GDB people about GNU Octave

Yeah, you are right. I think I'll be asking octave community first as it's a bit specific. Maybe I'll ask the other way around if a practical solution wouldn't be found
https://octave.discourse.group/t/attaching-with-gdb/3672

**Comment by korcankaraokcu** [comment] 2023-08-05 22:10
Open up the gdb console and run `handle SIGUSR1 nopass`. After this, send SIGUSR1 to the target from another terminal with `kill -10 <pid>`. This works for CLI but probably not a very good solution for PINCE since I’ve seen SIGUSR1 used by other processes before but it’s definitely a solution for processes that doesn’t, such as octave

I'll try to find a better and more generic solution for PINCE

**Comment by korcankaraokcu** [comment] 2023-08-06 14:09
GDB actually manages to stop the process once when you first attach to it. So, another solution would be to open up the MemoryViewer and set a breakpoint to the first address after attaching. You have to memorize the address or keep a gdb command ready, such as `break *<address>`

**Comment by MayeulC** [comment] 2023-08-09 14:05
> Open up the gdb console and run `handle SIGUSR1 nopass`. After this, send SIGUSR1 to the target from another terminal with `kill -10 <pid>`. This works for CLI but probably not a very good solution for PINCE since I’ve seen SIGUSR1 used by other processes before but it’s definitely a solution for processes that doesn’t, such as octave
> 
> I'll try to find a better and more generic solution for PINCE

Good find! If you need free signal slots, there are many "real-time signals" for user-defined behavior, a good overview exists in `signal (7)`. There is still a collision risk, but it's much less. A slight complication is that the range is dynamic, and `SIGRTMIN` should be queried from the libc. Maybe setting another signal by default would be safer? Or as an option? Possibly multiple signals as fallbacks?

```
(gdb) handle SIG53 nopass
$ killall -53 octave-gui
```

> So, another solution would be to open up the MemoryViewer and set a breakpoint to the first address after attaching.

I don't quite understand how that would help?

Reading around, the non-stop mode may be interesting to use, as it "interrupts" the inferior [differently](https://sourceware.org/gdb/onlinedocs/gdb/Non_002dStop-Mode.html). Alternatively, [background execution](https://sourceware.org/gdb/onlinedocs/gdb/Background-Execution.html#Background-Execution) may be another option?

```
(gdb) run&
(gdb) interrupt -a
(gdb) continue&
```
However, that seems to interact badly with command-line programs, at least when running them from GDB, as it takes over stdin/out. I'm no GDB expert at all, so I'm just throwing suggestions around :)

----
I must say that I don't really *need* to use PINCE with GNU Octave or a similar program, I was just confused by the behavior.

**Comment by korcankaraokcu** [comment] 2023-08-09 22:51
> If you need free signal slots, there are many "real-time signals" for user-defined behavior, a good overview exists in signal (7)

Thanks for the insight. Would definitely use if we switched from the default SIGINT. I don't think the main target would be console programs for pince but still, solving this could give us an interesting insight, such as the conversation we are having right now

> I don't quite understand how that would help?

According to my experience, gdb stops processes at functions like [poll](https://man7.org/linux/man-pages/man2/poll.2.html). Which makes sense as the default game loop would wait for a user input. You'll most likely stop at a function like poll for the first time when you attach. So, remembering the address and setting up a breakpoint there would most likely stop process again

> Reading around, the non-stop mode may be interesting to use, as it "interrupts" the inferior [differently](https://sourceware.org/gdb/onlinedocs/gdb/Non_002dStop-Mode.html). Alternatively, [background execution](https://sourceware.org/gdb/onlinedocs/gdb/Background-Execution.html#Background-Execution) may be another option?

We already use background execution, it has been actually implemented very recently. Unfortunately, that seems to have no effect on this issue. However, non-stop mode would maybe help but that'd probably mean a rewrite which I don't want to start right now. I also don't know how other features work with that

**Comment by korcankaraokcu** [comment] 2024-01-04 14:08
With https://github.com/korcankaraokcu/PINCE/commit/9d539c39f21e19622e3a722ffdfaca15f90e8ea6, you can now change the interruption signal via settings. I've used real time signals as you suggested. Closing the issue since a good solution was found

**Closed by korcankaraokcu** 2024-01-04 14:08 UTC
