### ISSUE TITLE
Freeze when using various features after using breakpoints

### ISSUE THREAD

**Issue by Madghostek** [korcankaraokcu/PINCE#160] opened 2023-01-08 14:43 UTC
Steps to reproduce:
1. Start PINCE, attach to a process
2. Set a breakpoint and make program hit it
3. Add a memory address to the cheat table, use "find out what reads/writes/accesses this address"
4. Program freezes

After restarting PINCE the issue persists, you also can't pause the program being debugged because PINCE freezes. After restarting the program being debugged the issue is gone.

I'm running Linux mint 20.3 with kernel 6.1.0

**Comment by korcankaraokcu** [comment] 2023-01-08 15:49
I can't seem to reproduce this on my end. Are you sure you are continuing after the breakpoint hits? Or maybe that feature is finding way too many addresses, like thousands per second. Can you provide an excerpt from console when the process freezes?

**Comment by Madghostek** [comment] 2023-01-08 21:57
https://user-images.githubusercontent.com/28148202/211221045-18d548d7-2b3c-471d-8ad0-1ebabbab3179.mp4

Here is video of me having the issue with console output, the only suspicious thing I see is `last command: ctrl+c`, but I didn't press it.

**Comment by korcankaraokcu** [comment] 2023-01-09 14:14
> trying to pause the inferior process also hangs

This might be related to gdb. Try to attach to the process with gdb only. Launch gdb and use the `attach` command with the pid of the process. My guess is that it blocks the `SIGINT`, which is used by gdb. We had a similar problem in #157

**Comment by korcankaraokcu** [comment] 2023-09-24 21:43
There has been a patch regarding this issue. Can you try that again?

**Comment by korcankaraokcu** [comment] 2023-10-06 16:00
> I can confirm it's gdb being unable to pause execution with ctrl+c

Yeah, the same problem with #157. Fortunately, there's a working solution in the same issue:
> Open up the gdb console and run `handle SIGUSR1 nopass`. After this, send SIGUSR1 to the target from another terminal with `kill -10 <pid>`

A secondary solution would be

> GDB actually manages to stop the process once when you first attach to it. So, another solution would be to open up the MemoryViewer and set a breakpoint to the first address after attaching. You have to memorize the address or keep a gdb command ready, such as `break *<address>`

**Comment by damajor** [comment] 2023-11-15 10:09
I think I ran into the same issue. It is pretty annoying :)

My steps to reproduce:

0. Open target process
1. Open Pince
2. Attach process
3. Find location
4. Add location to address table
5. Find out what accesses this address
6. Wait a bit and stop then use close button
7. If not frozen, repeat steps (5) and (6) more times

Freeze is almost always coming after 3rd or 4rth tries, and it happens even more faster if you kill & restart PINCE  without restarting the target process.

Here is the kind of error I have in console output:
```
Exception in thread Thread-12 (state_observe_thread):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/.../libpince/GDB_Engine.py", line 301, in state_observe_thread
    check_inferior_status()
  File "/home/.../PINCE/libpince/GDB_Engine.py", line 283, in check_inferior_status
    if bp_num and breakpoint_on_hit_dict[bp_num.group(1)] != type_defs.BREAKPOINT_ON_HIT.BREAK:
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: '1'
```
The `KeyError` is always matching the number of time I use "Find out what accesses this address" feature.

Unfortunately I was NOT able to recover using the workaround you mentioned in the previous post.

I hope this will help.

**Comment by korcankaraokcu** [comment] 2023-11-15 13:59
@damajor Thanks for the bug report but yours might be different than the original post. The issue above was about target not being able to process SIGINT, so it's a gdb related issue. Yours looks more like a pince related issue. If your target is not a console application or can process SIGINT properly, please open a new issue so we don't derail this one. Also, I'd like to see which process you are testing pince on, along with your system specs (distro info etc)

**Comment by korcankaraokcu** [comment] 2024-01-06 13:06
You can now choose the interruption signal via settings. Closing since it's a duplicate of #157

**Closed by korcankaraokcu** 2024-01-06 13:06 UTC
