### ISSUE TITLE
Fail to execute sh PINCE.sh after compiling 

### ISSUE THREAD

**Issue by rdcklinux** [korcankaraokcu/PINCE#81] opened 2020-07-06 21:09 UTC
SO: Ubuntu 19.04

```
Traceback (most recent call last):
  File "PINCE.py", line 31, in <module>
    from libPINCE import GuiUtils, SysUtils, GDB_Engine, type_defs
  File "/home/developer/Desarrollo/games/PINCE/libPINCE/GuiUtils.py", line 24, in <module>
    from . import SysUtils, type_defs, common_regexes
  File "/home/developer/Desarrollo/games/PINCE/libPINCE/SysUtils.py", line 32, in <module>
    from pygdbmi import gdbmiparser
ModuleNotFoundError: No module named 'pygdbmi'
```

**SOLUTION:**

* Edit **PINCE.sh** on line 25 and add -E parameter for to expose environment vars to privileged user.

Example:

`sudo -E python3 PINCE.py`

**Comment by Kellegram** [comment] 2020-07-06 21:18
Lmao, that's crazy, I literally just installed it and it failed too. I get random errors, the most common one is

```
Traceback (most recent call last):
  File "PINCE.py", line 32, in <module>
    from libPINCE.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libPINCE.libscanmem.scanmem'
```

**Comment by Kellegram** [comment] 2020-07-06 21:21
Your solution did not fix my issue unfortunately @rdcklinux

**Comment by korcankaraokcu** [comment] 2020-07-07 14:49
@rdcklinux I couldn't reproduce this error on my end with a clean installation but since your solution fixes your problem and it doesn't have any negative effects, I've committed it. Enjoy. I will be closing this for now, feel free to reopen if it occurs again.

@Kellegram The errors you get might not be related to his. Please open a new issue with the console log so we can see what's wrong with it.

**Closed by korcankaraokcu** 2020-07-07 14:49 UTC

**Comment by philenko** [comment] 2020-08-08 07:41
Same Issue on Ubuntu 20.04.1

`Traceback (most recent call last):
  File "PINCE.py", line 32, in <module>
    from libPINCE.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libPINCE.libscanmem.scanmem'`

**Comment by korcankaraokcu** [comment] 2020-08-14 05:13
@philenko I see that you've opened another issue about this, so I'll be continuing from there (#86)
