### ISSUE TITLE
PINCE totally locks down search interface

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#67] opened 2019-06-04 20:31 UTC
No matter what I try when I try to hack the memory of game via PINCE it outright refuses to do anything but show the debugger/memory (reader?), I'd like an option to ignore risks and just scan anyway, GameConqueror can get into the same memory just fine but it lacks the ability to search for values based on number of bits which I was trying to use PINCE for but everything is just permanently disabled
The game I'm trying is Dragon Quest Builders on RPCS3

**Comment by korcankaraokcu** [comment] 2019-06-04 20:38
Scanmem isnt integrated yet so the search interface is just a placeholder for now(it's even written on it)

Duplicate of #64, closing

**Closed by korcankaraokcu** 2019-06-04 20:38 UTC

**Comment by awsdert** [comment] 2019-06-04 21:01
But the thing is the interface did work until I had to reinstall my os

**Comment by korcankaraokcu** [comment] 2019-06-04 21:05
Wait a sec, are we talking about the same interface? The one with disabled "next scan" and "new scan" buttons right? If so, even if the interface was enabled back in the day, it was never functioning since scanmem wasnt implemented. If you are talking about another interface, please describe in detail

**Comment by awsdert** [comment] 2019-06-04 21:07
same interface, don't know how it worked but it did, I used it for a steam game I think

**Comment by korcankaraokcu** [comment] 2019-06-04 21:09
Huh, that's weird because scanmem was **never** implemented. Are you sure that you arent confusing interfaces of GC and PINCE back at the time?

**Comment by awsdert** [comment] 2019-06-04 21:12
Nah, hated GC (still hate it) so I never used it until pince started misbehaving, I assumed it was working because you had it hooked into gdb or something, did you perhaps have some untested makeshift code in there or something?

**Comment by korcankaraokcu** [comment] 2019-06-04 21:21
Actually I didnt make many changes to PINCE as I was busy with ctfs&work so there shouldn't be any recent untested code. I even recently used it for a ctf challenge in ParrotOS virtual machine, it worked flawlessly. Maybe I didnt get your problem properly. Are you saying that not only scan menu isnt working but the entire GUI halts? or am I getting it wrong?

**Comment by awsdert** [comment] 2019-06-04 21:26
scan part of the GUI is just plain disabled, I thought that maybe some code shoved in at the early stages to hook into the /proc/<PID>/mem file or something just happened to work for me before my system was destroyed (by something I did, not pince) and I was forced to reinstall, I managed to copy over my copy of pince at the time by keeping anything not system related on other drives and when I booted pince after the GUI had stopped allowing me to use the scan facilities, I thought it was just an incompatibility due to reinstalled system so I deleted that copy of pince and recloned/installed the current pince but still had the same problem

**Comment by korcankaraokcu** [comment] 2019-06-04 22:33
No, it's been disabled for a long time now, since it's not implemented I've completely disabled it with a text "this is a placeholder" on it. It's really weird that you remember it as enabled in the past. You made me double check my code 😄 I was like, ***did I just implement scanmem and remove it afterwards and dont remember it?*** Fortunately, I havent gone insane yet, so it's not implemented. It's not a bug, just lack of a feature

**Comment by awsdert** [comment] 2019-06-04 23:17
So not even some half-assed code that has a TODO on the parts that should be checking for failures or something? That's the only thing I can think of for why it was working for me even if unintentionally, either way I gotta get some sleep now so this is my last response for the night
